# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f176dcf2849e8e048aae7f72b2c9cbf2949f21bf9c59a5fccaf248de3a8e3f76fd0c025199750ea46195526d07b7afb40c1f42a24b6de889b67e0d2dfa5aed40

test:
  secret_key_base: 3829b3c6b2b725e016c37d8ad66660c3aeaae99c82c45d33dea5d36017681131f77b1b9b736311501c40fbeb578af962a5eb992ca6ceb6bd8dbae86e7231bb0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
